<?php

$instructions_request = '<br><strong>Proměnné poptávky</strong>';
$instructions_request .= '<br><code>%request_name%</code>, <code>%request_category%</code>, <code>%request_admin_edit_url%</code>, <code>%request_text%</code>, <code>%request_author_name%</code>, <code>%request_author_email%</code>, <code>%request_preview_url%</code>, <code>%request_url%</code>, <code>%request_expiration_url%</code><br>';

$instructions_professional = '<br><strong>Proměnné partnera</strong>';
$instructions_professional .= '<br><code>%partner_name%</code>, <code>%partner_unsubscribe_category_url%</code>, <code>%partner_unsubscribe_all_url%</code><br>';

$instructions_message = '<br><strong>Proměnné reakce</strong>';
$instructions_message .= '<br><code>%message_name%</code>, <code>%message_email%</code>, <code>%message_text%</code><br>';

$instructions_author_footer = 'Za touto zprávou se zobrazí patička s expiračním odkazem (viz níže)<br>';

if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
    'key' => 'group_5dc2c3c920d55',
    'title' => 'Nastavení mailingu poptávek',
    'fields' => array(
      array(
        'key' => 'field_5dc2c47283ead',
        'label' => 'E-mail zadavateli po vložení poptávky ke schválení',
        'name' => 'request_new_author',
        'type' => 'group',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dc2c4d883eae',
            'label' => 'Předmět',
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dc2c4e583eaf',
            'label' => 'Zpráva',
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => $instructions_author_footer,
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dc2c69a39ef6',
        'label' => 'E-mail adminovi po vložení poptávky ke schválení',
        'name' => 'request_new_admin',
        'type' => 'group',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dc2c69a39ef7',
            'label' => 'Předmět',
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dc2c69a39ef8',
            'label' => 'Zpráva',
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dc2c7c1f354b',
        'label' => 'E-mail zadavateli po schválení poptávky',
        'name' => 'request_approve_author',
        'type' => 'group',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dc2c7c1f354c',
            'label' => 'Předmět',
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dc2c7c1f354d',
            'label' => 'Zpráva',
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => $instructions_author_footer,
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dc2c807f354e',
        'label' => 'E-mail partnerovi po schválení poptávky',
        'name' => 'request_approve_professional',
        'type' => 'group',
        'instructions' => $instructions_request . $instructions_professional,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dc2c807f354f',
            'label' => 'Předmět',
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dc2c807f3550',
            'label' => 'Zpráva',
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dce823ef51cc',
        'label' => 'E-mail zadavateli s odpovědí na poptávku',
        'name' => 'request_message_author',
        'type' => 'group',
        'instructions' => $instructions_request . $instructions_message,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dce823ef51cd',
            'label' => 'Předmět',
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dce823ef51ce',
            'label' => 'Zpráva',
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dce82dff51cf',
        'label' => 'E-mail zadavateli po expiraci poptávky',
        'name' => 'request_expired_author',
        'type' => 'group',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dce82dff51d0',
            'label' => 'Předmět',
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dce82dff51d1',
            'label' => 'Zpráva',
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dce832ef51d2',
        'label' => 'E-mail partnerovi po odhlášení z mailingu',
        'name' => 'request_unsubscribed_professional',
        'type' => 'group',
        'instructions' => $instructions_professional,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dce832ef51d3',
            'label' => 'Předmět',
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dce832ef51d4',
            'label' => 'Zpráva',
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dce83eff51d6',
        'label' => 'Patička e-mailu zadavateli s expiračním odkazem',
        'name' => 'request_footer_author',
        'type' => 'textarea',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'requests-mailing',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));
  
  endif;