<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_59cab5068ad1b',
	'title' => __( 'Kategorie', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_59db64355c03c',
			'label' => __( 'Titulek', 'shp-partneri' ),
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59cab50932231',
			'label' => __( 'Obrázek', 'shp-partneri' ),
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category_professionals',
			),
		),
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category_plugins',
			),
		),
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category_tools',
			),
		),
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category_requests',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59e8b759957bd',
	'title' => __( 'Nastavení napojení', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_59f20b6428ac3',
			'label' => __( 'Perex na domovské stránce', 'shp-partneri' ),
			'name' => 'perexPlugin',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_59e8b7599874e',
			'label' => __( 'Nadpis popisu', 'shp-partneri' ),
			'name' => 'titleDescriptionPlugin',
			'type' => 'text',
			'instructions' => __( 'Bude zobrazeno jako nadpis popisu příspěvku.', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59e8b759987e1',
			'label' => __( 'Nadpis přínosu', 'shp-partneri' ),
			'name' => 'titleBenefitPlugin',
			'type' => 'text',
			'instructions' => __( 'Bude zobrazeno jako nadpis přínosu příspěvku.', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'plugin-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59e8b782acbbd',
	'title' => __( 'Nastavení nástrojů', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_59f20b48e40ac',
			'label' => __( 'Perex na domovské stránce', 'shp-partneri' ),
			'name' => 'perexTool',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_59e8b782af9a3',
			'label' => __( 'Nadpis popisu', 'shp-partneri' ),
			'name' => 'titleDescriptionTool',
			'type' => 'text',
			'instructions' => __( 'Bude zobrazeno jako nadpis popisu příspěvku.', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59e8b782afa4a',
			'label' => __( 'Nadpis přínosu', 'shp-partneri' ),
			'name' => 'titleBenefitTool',
			'type' => 'text',
			'instructions' => __( 'Bude zobrazeno jako nadpis přínosu příspěvku.', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'tool-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59e8b36e766a4',
	'title' => __( 'Nastavení profesionálů', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_59f20a6f1b99c',
			'label' => __( 'Perex na domovské stránce', 'shp-partneri' ),
			'name' => 'perexProfessional',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_59e8b58c2df87',
			'label' => __( 'Nadpis popisu', 'shp-partneri' ),
			'name' => 'titleDescriptionProfessional',
			'type' => 'text',
			'instructions' => __( 'Bude zobrazeno jako nadpis popisu příspěvku.', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59e8b5d82df88',
			'label' => __( 'Nadpis přínosu', 'shp-partneri' ),
			'name' => 'titleBenefitProfessional',
			'type' => 'text',
			'instructions' => __( 'Bude zobrazeno jako nadpis přínosu příspěvku.', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'professional-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59f7359232f8a',
	'title' => __( 'Patička', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_59f735a17add5',
			'label' => __( 'Text v patičce', 'shp-partneri' ),
			'name' => 'themeFooterText',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-paticka',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59fccbc35c759',
	'title' => __( 'Domovská stránka', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_59fccbc35fc39',
			'label' => __( 'Hero text', 'shp-partneri' ),
			'name' => 'themeHomepageHeroText',
			'type' => 'text',
			'instructions' => __( 'Text bude použit v hero boxu a meta tagu description domovské stánky. Pro zobrazení celkového počtu profilů vložte: %count%', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-obecne',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5a006f0334694',
	'title' => __( 'Nastavení', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_5a006f06b51ca',
			'label' => __( 'Google Tag Manager ID', 'shp-partneri' ),
			'name' => 'themeGTMId',
			'type' => 'text',
			'instructions' => __( 'Ve tvaru GTM-XXXX', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-nastaveni',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5a0355b835bd6',
	'title' => __( 'Open graph', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_5a0355c7459b1',
			'label' => __( 'Open graph obrázek', 'shp-partneri' ),
			'name' => 'themeOpenGraphImage',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-obecne',
			),
		),
	),
	'menu_order' => 7,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59f202ab3988a',
	'title' => __( 'Reference', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_59f208137ad64',
			'label' => __( 'Zobrazit na domovské stránce', 'shp-partneri' ),
			'name' => 'themeReferenceShowHomepage',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => __( 'Zobrazit', 'shp-partneri' ),
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59f202b7c2217',
			'label' => __( 'Jméno', 'shp-partneri' ),
			'name' => 'themeReferenceName',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59f20310c2218',
			'label' => __( 'Pozice', 'shp-partneri' ),
			'name' => 'themeReferencePosition',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59f20330c221a',
			'label' => __( 'Web', 'shp-partneri' ),
			'name' => 'themeReferenceUrl',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_59f2055a15c9e',
			'label' => __( 'Fotka', 'shp-partneri' ),
			'name' => 'themeReferenceImage',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_59f20345c221b',
			'label' => __( 'Text', 'shp-partneri' ),
			'name' => 'themeReferenceText',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 5,
			'new_lines' => 'wpautop',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-obecne',
			),
		),
	),
	'menu_order' => 10,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_BaPbMgUbyKxHo',
	'title' => __( 'Staň se partnerem', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_MItgCUEMLhWNJ',
			'label' => __( 'Titulek', 'shp-partneri' ),
			'name' => 'themeBecomePartnerTitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
        array (
			'key' => 'field_zncNuZFoXb2Io',
			'label' => __( 'Text', 'shp-partneri' ),
			'name' => 'themeBecomePartnerContent',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
        array (
			'key' => 'field_IpkTta64keTt2',
			'label' => __( 'Ilustrační obrázek', 'shp-partneri' ),
			'name' => 'themeBecomePartnerImage',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
        /*array (
			'key' => 'field_59f7532c4dude',
			'label' => __( 'Text na tlačítku', 'shp-partneri' ),
			'name' => 'themeBecomePartnerButtonText',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),*/

	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-obecne',
			),
		),
	),
	'menu_order' => 12,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59fc7890159c2',
	'title' => __( 'Email pro žádost o zařazení mezi Shoptet partnery', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_59fc78901902c',
			'label' => __( 'E-mail', 'shp-partneri' ),
			'name' => 'themeCtaMailAddress',
			'type' => 'email',
			'instructions' => __( 'Adresa příjemce e-mailu', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_59fc789019067',
			'label' => __( 'Předmět', 'shp-partneri' ),
			'name' => 'themeCtaMailSubject',
			'type' => 'text',
			'instructions' => __( 'Předvyplněný předmět e-mailu', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fc78901909e',
			'label' => __( 'Text zprávy', 'shp-partneri' ),
			'name' => 'themeCtaMailBody',
			'type' => 'textarea',
			'instructions' => __( 'Předvyplněný text e-mailu', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 5,
			'new_lines' => 'br',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-obecne',
			),
		),
	),
	'menu_order' => 15,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59fc799f9093c',
	'title' => __( 'Výzva k akci v seznamu', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_59fc799f93b92',
			'label' => __( 'Zobrazit v seznamu profilů', 'shp-partneri' ),
			'name' => 'themeCtaShowList',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => __( 'Zobrazit', 'shp-partneri' ),
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59fc799f93c74',
			'label' => __( 'Titulek', 'shp-partneri' ),
			'name' => 'themeListCtaTitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fc799f93ce1',
			'label' => __( 'Text na tlačítku', 'shp-partneri' ),
			'name' => 'themeListCtaButtonText',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-obecne',
			),
		),
	),
	'menu_order' => 20,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));



acf_add_local_field_group(array (
	'key' => 'group_K4M9DdbzGs3Vt',
	'title' => __( 'Stížnost na partnera', 'shp-partneri' ),
	'fields' => array (
        array (
			'key' => 'field_6XyApEcCt8z2b',
			'label' => __( 'Titulek', 'shp-partneri' ),
			'name' => 'themeComplaintTitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
        array (
			'key' => 'field_2d6tuB9cdM4AC',
			'label' => __( 'Text', 'shp-partneri' ),
			'name' => 'themeComplaintContent',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
        array (
			'key' => 'field_3d6tuC9cdM5AC',
			'label' => __( 'Kontaktní formulář (shortcode)', 'shp-partneri' ),
			'name' => 'themeComplaintContact',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
        array (
			'key' => 'field_pU3bf7YGr38DC',
			'label' => __( 'Text u kontaktního formuláře', 'shp-partneri' ),
			'name' => 'themeComplaintContactText',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		/*array (
			'key' => 'field_HX3j467EbMUWc',
			'label' => __( 'Text na tlačítku', 'shp-partneri' ),
			'name' => 'themeComplaintButtonText',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),*/
		/*array (
			'key' => 'field_7d2rBp3PxdLds',
			'label' => __( 'E-mail', 'shp-partneri' ),
			'name' => 'themeComplaintMailAddress',
			'type' => 'email',
			'instructions' => __( 'Adresa příjemce e-mailu', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),*/
		/*array (
			'key' => 'field_pU4bc7YGr37DG',
			'label' => __( 'Předmět', 'shp-partneri' ),
			'name' => 'themeComplaintMailSubject',
			'type' => 'text',
			'instructions' => __( 'Předvyplněný předmět e-mailu', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),*/
		/*array (
			'key' => 'field_x7sL9Ghtep3YV',
			'label' => __( 'Text zprávy', 'shp-partneri' ),
			'name' => 'themeComplaintMailBody',
			'type' => 'textarea',
			'instructions' => __( 'Předvyplněný text e-mailu', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 5,
			'new_lines' => 'br',
		),*/
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-obecne',
			),
		),
	),
	'menu_order' => 25,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5a03324589bf8',
	'title' => __( 'Stránka 404', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_5a033272c5fd0',
			'label' => __( 'Text', 'shp-partneri' ),
			'name' => 'themeNotFoundText',
			'type' => 'wysiwyg',
			'instructions' => __( 'Tento text se zobrazí větším písmem pod nadpisem', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-obecne',
			),
		),
	),
	'menu_order' => 30,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59r74pffe3d26',
	'title' => __( 'Shoptet partneři - odznaky', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_iLLf05wDuSG7A',
			'label' => __( 'Titulek', 'shp-partneri' ),
			'name' => 'themeBadgesTitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
        array (
			'key' => 'field_nDTLivNyCdvWR',
			'label' => __( 'Text (nyní zakomentováno, nebude vidět)', 'shp-partneri' ),
			'name' => 'themeBadgesContent',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_e1HSLd0DJEVC4',
			'label' => __( 'Zlatý partner', 'shp-partneri' ),
			'name' => 'themeBadgesGoldText',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
        array (
			'key' => 'field_XMzmZ28kWWx7x',
			'label' => __( 'Stříbrný partner', 'shp-partneri' ),
			'name' => 'themeBadgesSilverText',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
        array (
			'key' => 'field_CG860wuZsx47X',
			'label' => __( 'Bronzový partner', 'shp-partneri' ),
			'name' => 'themeBadgesBronzeText',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),

	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-obecne',
			),
		),
	),
	'menu_order' => 35,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59r61pfbr3d26',
	'title' => __( 'Partnerský formulář', 'shp-partneri' ),
	'fields' => array (
		array (
			'key' => 'field_iSSf05wMeSG7B',
			'label' => __( 'Formulář ID', 'shp-partneri' ),
			'name' => 'themePartnerContactForm',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),

	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-obecne',
			),
		),
	),
	'menu_order' => 40,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cb4b7d67cd75',
	'title' => __( 'Kontakt', 'shp-partneri' ),
	'fields' => array(
		array(
			'key' => 'field_5cb4b7dd2ee57',
			'label' => __( 'ID kontaktního formuláře', 'shp-partneri' ),
			'name' => 'contact_form_id',
			'type' => 'number',
			'instructions' => __( 'Mělo by odpovídat ID kontaktního formuláře z políčka "Kontaktní formulář (shortcode)".', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5d120e9148c49',
			'label' => __( 'Popis u vstupního formuláře', 'shp-partneri' ),
			'name' => 'onboarding_description',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-obecne',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ca5e9460cbb1',
	'title' => __( 'Mailing', 'shp-partneri' ),
	'fields' => array(
		array(
			'key' => 'field_5ca5e95929967',
			'label' => __( 'Odesílatel e-mailů', 'shp-partneri' ),
			'name' => 'email_from',
			'type' => 'text',
			'instructions' => __( 'Ve tvaru "Jméno &lt;email&gt;"', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ca5e9b129968',
			'label' => __( 'Příjemce e-mailu s upozorněním o nově autorizovaném hodnocení', 'shp-partneri' ),
			'name' => 'authorized_review_email_recipient',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-nastaveni',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d9f2e530aeec',
	'title' => __( 'Poptávka', 'shp-partneri' ),
	'fields' => array(
		array(
			'key' => 'field_5d9f2ebf8e646',
			'label' => __( 'Vaše jméno', 'shp-partneri' ),
			'name' => 'author_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5da06f824e26a',
			'label' => __( 'Váš e-mail', 'shp-partneri' ),
			'name' => 'author_email',
			'type' => 'email',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '@',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5d9f2efc8e647',
			'label' => __( 'URL projektu', 'shp-partneri' ),
			'name' => 'url',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5d9f2f4a8e648',
			'label' => __( 'Kategorie poptávky', 'shp-partneri' ),
			'name' => 'category',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category_requests',
			'field_type' => 'select',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array(
			'key' => 'field_5d9f2fbd8e64a',
			'label' => __( 'E-shop na Shoptetu', 'shp-partneri' ),
			'name' => 'is_shoptet',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => __( 'Provozuji e-shop na Shoptetu', 'shp-partneri' ),
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'request',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ca1ee8b9e2c5',
	'title' => __( 'Hodnocení', 'shp-partneri' ),
	'fields' => array(
		array(
			'key' => 'field_5ca1f16a65b32',
			'label' => __( 'Autor ověřil své hodnocení', 'shp-partneri' ),
			'name' => 'authenticated',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y g:i a',
			'return_format' => 'd/m/Y g:i a',
			'first_day' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'comment',
				'operator' => '==',
				'value' => 'profesionalove',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d10a8e1afc08',
	'title' => __( 'Základní', 'shp-partneri' ),
	'fields' => array(
		array(
			'key' => 'field_59ca39157537c',
			'label' => __( 'E-mail', 'shp-partneri' ),
			'name' => 'emailAddress',
			'type' => 'email',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '@',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_59d39f0557b4d',
			'label' => __( 'Prověřen', 'shp-partneri' ),
			'name' => 'isVerified',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => __( 'Zobrazit odznak prověření', 'shp-partneri' ),
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_mmmvatu2lvzex',
			'label' => __( 'Úrověň prověření', 'shp-partneri' ),
			'name' => 'verifiedLevel',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'bronzový' => __( 'bronzový', 'shp-partneri' ),
				'stříbrný' => __( 'stříbrný', 'shp-partneri' ),
				'zlatý' => __( 'zlatý', 'shp-partneri' ),
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e1604b43d097',
			'label' => __( 'Tvůrce blank šablon', 'shp-partneri' ),
			'name' => 'blank_template_creator',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => __( 'Partner je proškolen v tvorbě blank šablon', 'shp-partneri' ),
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_87asdc350933f',
			'label' => __( 'Partner manager', 'shp-partneri' ),
			'name' => 'partnerManager',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Není' => __( 'Není', 'shp-partneri' ),
				'Marcela Coufalová' => 'Marcela Coufalová',
				'Ondřej Mikoláš' => 'Ondřej Mikoláš',
				'Katarína Bukovini' => 'Katarína Bukovini',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => __( 'Není', 'shp-partneri' ),
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_59ca41f49c478',
			'label' => __( 'Cena (zastaralé)', 'shp-partneri' ),
			'name' => 'price',
			'type' => 'text',
			'instructions' => __( 'Toto pole je zde pouze z historických důvodů. Vyplňte prosím pole s cenou níže v tomto formuláři.', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5d8fa83ae54bf',
			'label' => __( 'Zpráva z kontaktního formuláře', 'shp-partneri' ),
			'name' => 'message',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'profesionalove',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d109cc9c2b65',
	'title' => __( 'Partner', 'shp-partneri' ),
	'fields' => array(
		array(
			'key' => 'field_5d10a24f0b5e7',
			'label' => __( 'Kategorie', 'shp-partneri' ),
			'name' => 'category',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category_professionals',
			'field_type' => 'select',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array(
			'key' => 'field_59ca38b07537a',
			'label' => __( 'URL vašeho webu', 'shp-partneri' ),
			'name' => 'url',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59ca38cc7537b',
			'label' => __( 'Telefon', 'shp-partneri' ),
			'name' => 'phoneNumber',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59ca39287537d',
			'label' => __( 'IČO', 'shp-partneri' ),
			'name' => 'cin',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59edcc260922d',
			'label' => __( 'DIČ', 'shp-partneri' ),
			'name' => 'tin',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5d3ebac0c8049',
			'label' => __( 'Země', 'shp-partneri' ),
			'name' => 'country',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'cz' => __( 'Česká republika', 'shp-partneri' ),
				'sk' => __( 'Slovensko', 'shp-partneri' ),
			),
			'default_value' => array(
				0 => 'cz',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'array',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d3ebb18c804a',
			'label' => __( 'Kraj', 'shp-partneri' ),
			'name' => 'region',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d3ebac0c8049',
						'operator' => '==',
						'value' => 'cz',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'Hlavní město Praha',
				1 => 'Jihočeský kraj',
				2 => 'Jihomoravský kraj',
				3 => 'Karlovarský kraj',
				4 => 'Kraj Vysočina',
				5 => 'Královéhradecký kraj',
				6 => 'Liberecký kraj',
				7 => 'Moravskoslezský kraj',
				8 => 'Olomoucký kraj',
				9 => 'Pardubický kraj',
				10 => 'Plzeňský kraj',
				11 => 'Středočeský kraj',
				12 => 'Ústecký kraj',
				13 => 'Zlínský kraj',
			),
			'default_value' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'array',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d3ebb6bc804b',
			'label' => __( 'Kraj', 'shp-partneri' ),
			'name' => 'region',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d3ebac0c8049',
						'operator' => '==',
						'value' => 'sk',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				14 => 'Bratislavský kraj',
				15 => 'Trnavský kraj',
				16 => 'Trenčínský kraj',
				17 => 'Nitranský kraj',
				18 => 'Žilinský kraj',
				19 => 'Banskobystrický kraj',
				20 => 'Prešovský kraj',
				21 => 'Košický kraj',
			),
			'default_value' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'array',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_59ca4bf803c36',
			'label' => __( 'Facebook', 'shp-partneri' ),
			'name' => 'facebook',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59ca4c1603c37',
			'label' => __( 'Twitter', 'shp-partneri' ),
			'name' => 'twitter',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_69fa4c4237d38',
			'label' => __( 'Instagram', 'shp-partneri' ),
			'name' => 'instagram',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59ca4c2503c38',
			'label' => __( 'LinkedIn', 'shp-partneri' ),
			'name' => 'linkedin',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5d10c3f29b87b',
			'label' => __( 'Fotka', 'shp-partneri' ),
			'name' => 'image',
			'type' => 'image',
			'instructions' => __( 'Prosím vložte fotku v minimálním rozlišení 400 x 400 px. Soubor nahrajte ve formátu jpg, png nebo gif. Maximální velikost souboru je 5 MB.', 'shp-partneri' ),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'uploadedTo',
			'min_width' => 400,
			'min_height' => 400,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => 5,
			'mime_types' => 'jpg,png,gif',
		),
		array(
			'key' => 'field_5d8217ec31ab1',
			'label' => __( 'Měna hodinové sazby', 'shp-partneri'),
			'name' => 'price_currency',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'CZK' => 'Kč',
				'EUR' => '€',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d3f026f0cef2',
			'label' => __( 'Hodinová sazba', 'shp-partneri'),
			'name' => 'price_per_hour_display',
			'type' => 'number',
			'instructions' => __( 'Uveďte svou hodinovou sazbu bez DPH ve vámi vybrané měně.', 'shp-partneri'),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5d82194831ab2',
			'label' => __( 'Plátcovství DPH', 'shp-partneri'),
			'name' => 'vat_payer',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => __( 'Jsem plátce DPH', 'shp-partneri'),
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d3f02d50cef4',
			'label' => __( 'Další informace k ceně', 'shp-partneri'),
			'name' => 'price_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59ca425ee9a9e',
			'label' => __( 'O mně', 'shp-partneri'),
			'name' => 'description',
			'type' => 'wysiwyg',
			'instructions' => __( 'Popište v pár větách sebe a svou práci.', 'shp-partneri'),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_59e8ac0d91d4b',
			'label' => __( 'Co umím?', 'shp-partneri'),
			'name' => 'benefit',
			'type' => 'wysiwyg',
			'instructions' => __( 'Popište ve dvou odstavcích, co klientům můžete nabídnout a v čem jste dobrý. Nebojte se pochválit.', 'shp-partneri'),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_59cab1b28ed7f',
			'label' => __( 'Doporučení', 'shp-partneri'),
			'name' => 'recommendations',
			'type' => 'repeater',
			'instructions' => __( 'Vložte sem doporučení od některých vašich klientů (ideálně klientů fungujících na platformě Shoptet).', 'shp-partneri'),
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 1,
			'max' => 3,
			'layout' => 'block',
			'button_label' => __( 'Přidat doporučení', 'shp-partneri'),
			'sub_fields' => array(
				array(
					'key' => 'field_59cab2018ed82',
					'label' => __( 'Text doporučení', 'shp-partneri'),
					'name' => 'text',
					'type' => 'textarea',
					'instructions' => __( 'Vložte cca 2 věty doporučení', 'shp-partneri'),
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_59cab1d88ed80',
					'label' => __( 'Jméno klienta', 'shp-partneri'),
					'name' => 'name',
					'type' => 'text',
					'instructions' => __( 'Klienta budeme odkazovat pod doporučením, proto potřebujeme jeho jméno a pozici ve firmě.', 'shp-partneri'),
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_59e8a72b37f8d',
					'label' => __( 'Pozice klienta', 'shp-partneri'),
					'name' => 'position',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_59cab1e98ed81',
					'label' => __( 'Web klienta', 'shp-partneri'),
					'name' => 'url',
					'type' => 'text',
					'instructions' => __( 'A také webovou adresu.', 'shp-partneri'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_59ca4ec3995cd',
			'label' => __( 'Další reference', 'shp-partneri'),
			'name' => 'references',
			'type' => 'repeater',
			'instructions' => __( 'Vložte zde loga svých dalších referenčních klientů (odlišných od uvedených v Doporučení výše). Klienti by měli ideálně zase hlavně klienty fungující na platformě Shoptet. V medailonku vypadají loga moc pěkně, proto je, prosím, nevynechejte.', 'shp-partneri'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => __( 'Přidat logo', 'shp-partneri'),
			'sub_fields' => array(
				array(
					'key' => 'field_59ca4ed2995ce',
					'label' => __( 'Název', 'shp-partneri'),
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_59ca4ef1995cf',
					'label' => __( 'Logo', 'shp-partneri'),
					'name' => 'logo',
					'type' => 'image',
					'instructions' => __( 'JPG, PNG nebo GIF. Max. 3 MB. Min. 200 x 200 px.', 'shp-partneri' ),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => 200,
					'min_height' => 200,
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => 3,
					'mime_types' => 'jpg,png,gif',
				),
				array(
					'key' => 'field_59ca4f01995d0',
					'label' => __( 'URL odkazu', 'shp-partneri' ),
					'name' => 'url',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'profesionalove',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5db082d1318ea',
	'title' => __( 'Mailing poptávek', 'shp-partneri' ),
	'fields' => array(
		array(
			'key' => 'field_5db082de1cb01',
			'label' => __( 'Stav mailingu', 'shp-partneri' ),
			'name' => 'disable_mailing',
			'type' => 'true_false',
			'instructions' => __( 'Pokud je mailing vypnutý, partner nebude dostávat žádné e-maily s poptávkami.', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => __( 'Vypnout mailing', 'shp-partneri' ),
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5db0834a1cb02',
			'label' => __( 'Odhlášené kategorie', 'shp-partneri' ),
			'name' => 'unsubscribed_categories',
			'type' => 'taxonomy',
			'instructions' => __( 'Partnerovi budou chodit na e-mail poptávky dle kategorií, ke kterým je přiřazen. Zde je možné některou z kategorií odhlásit.', 'shp-partneri' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category_professionals',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'profesionalove',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
