<?php

$instructions_request = '<br><strong>' . __( 'Proměnné poptávky', 'shp-partneri' ) . '</strong>';
$instructions_request .= '<br><code>%request_name%</code>, <code>%request_category%</code>, <code>%request_admin_edit_url%</code>, <code>%request_text%</code>, <code>%request_author_name%</code>, <code>%request_author_email%</code>, <code>%request_preview_url%</code>, <code>%request_url%</code>, <code>%request_expiration_url%</code><br>';

$instructions_professional = '<br><strong>' . __( 'Proměnné partnera', 'shp-partneri' ) . '</strong>';
$instructions_professional .= '<br><code>%partner_name%</code>, <code>%partner_unsubscribe_category_url%</code>, <code>%partner_unsubscribe_all_url%</code><br>';

$instructions_message = '<br><strong>' . __( 'Proměnné reakce', 'shp-partneri' ) . '</strong>';
$instructions_message .= '<br><code>%message_name%</code>, <code>%message_email%</code>, <code>%message_text%</code><br>';

$instructions_author_footer = __( 'Za touto zprávou se zobrazí patička s expiračním odkazem (viz níže)<br>', 'shp-partneri' );

if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
    'key' => 'group_5dc2c3c920d55',
    'title' => __( 'Nastavení mailingu poptávek', 'shp-partneri' ),
    'fields' => array(
      array(
        'key' => 'field_5dc2c47283ead',
        'label' => __( 'E-mail zadavateli po vložení poptávky ke schválení', 'shp-partneri' ),
        'name' => 'request_new_author',
        'type' => 'group',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dc2c4d883eae',
            'label' => __( 'Předmět', 'shp-partneri' ),
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dc2c4e583eaf',
            'label' => __( 'Zpráva', 'shp-partneri' ),
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => $instructions_author_footer,
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dc2c69a39ef6',
        'label' => __( 'E-mail adminovi po vložení poptávky ke schválení', 'shp-partneri' ),
        'name' => 'request_new_admin',
        'type' => 'group',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5fd75fcf9c6c6',
            'label' => __('Aktivováno', 'shp-partneri'),
            'name' => 'is_enabled',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => __('E-mail aktivován', 'shp-partneri'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
          array(
            'key' => 'field_5dc2c69a39ef7',
            'label' => __( 'Předmět', 'shp-partneri' ),
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dc2c69a39ef8',
            'label' => __( 'Zpráva', 'shp-partneri' ),
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dc2c7c1f354b',
        'label' => __( 'E-mail zadavateli po schválení poptávky', 'shp-partneri' ),
        'name' => 'request_approve_author',
        'type' => 'group',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dc2c7c1f354c',
            'label' => __( 'Předmět', 'shp-partneri' ),
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dc2c7c1f354d',
            'label' => __( 'Zpráva', 'shp-partneri' ),
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => $instructions_author_footer,
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5aa2c7c1ac54b',
        'label' => __( 'E-mail zadavateli s připomenutím (po 7 dnech)', 'shp-partneri' ),
        'name' => 'request_remind_author',
        'type' => 'group',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5ac2c7cbfb54c',
            'label' => __( 'Předmět', 'shp-partneri' ),
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5cc2cac1f3541',
            'label' => __( 'Zpráva', 'shp-partneri' ),
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => $instructions_author_footer,
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5aa2caaaac54b',
        'label' => __( 'E-mail zadavateli s připomenutím o duplikaci (po 14 dnech)', 'shp-partneri' ),
        'name' => 'request_remind_before_sync_author',
        'type' => 'group',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5ac2c7cbfcccc',
            'label' => __( 'Předmět', 'shp-partneri' ),
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_aaa2cac1f3541',
            'label' => __( 'Zpráva', 'shp-partneri' ),
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => $instructions_author_footer,
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dc2c7c1aa54b',
        'label' => __( 'E-mail zadavateli po schválení externí poptávky', 'shp-partneri' ),
        'name' => 'request_approve_author_external',
        'type' => 'group',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5ac2cac1f354c',
            'label' => __( 'Předmět', 'shp-partneri' ),
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5db2c7b1fc54d',
            'label' => __( 'Zpráva', 'shp-partneri' ),
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => $instructions_author_footer,
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dc2c807f354e',
        'label' => __( 'E-mail partnerovi po schválení poptávky', 'shp-partneri' ),
        'name' => 'request_approve_professional',
        'type' => 'group',
        'instructions' => $instructions_request . $instructions_professional,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dc2c807f354f',
            'label' => __( 'Předmět', 'shp-partneri' ),
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dc2c807f3550',
            'label' => __( 'Zpráva', 'shp-partneri' ),
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dce823ef51cc',
        'label' => __( 'E-mail zadavateli s odpovědí na poptávku', 'shp-partneri' ),
        'name' => 'request_message_author',
        'type' => 'group',
        'instructions' => $instructions_request . $instructions_message,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dce823ef51cd',
            'label' => __( 'Předmět', 'shp-partneri' ),
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dce823ef51ce',
            'label' => __( 'Zpráva', 'shp-partneri' ),
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dce82dff51cf',
        'label' => __( 'E-mail zadavateli po expiraci poptávky', 'shp-partneri' ),
        'name' => 'request_expired_author',
        'type' => 'group',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dce82dff51d0',
            'label' => __( 'Předmět', 'shp-partneri' ),
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dce82dff51d1',
            'label' => __( 'Zpráva', 'shp-partneri' ),
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dce832ef51d2',
        'label' => __( 'E-mail partnerovi po odhlášení z mailingu', 'shp-partneri' ),
        'name' => 'request_unsubscribed_professional',
        'type' => 'group',
        'instructions' => $instructions_professional,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_5dce832ef51d3',
            'label' => __( 'Předmět', 'shp-partneri' ),
            'name' => 'subject',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5dce832ef51d4',
            'label' => __( 'Zpráva', 'shp-partneri' ),
            'name' => 'message',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'delay' => 0,
          ),
        ),
      ),
      array(
        'key' => 'field_5dce83eff51d6',
        'label' => __( 'Patička e-mailu zadavateli s expiračním odkazem', 'shp-partneri' ),
        'name' => 'request_footer_author',
        'type' => 'textarea',
        'instructions' => $instructions_request,
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'requests-mailing',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));
  
  endif;